### ISSUE TITLE
delivery method

### ISSUE THREAD

**Issue by Altanb1337** [extatent/Growtopia-Stealer-Library#3]
webhook not safe anymore, who get webhook url can delete the webhook with just 5 line code so how about add php delivery method? if you can would be good sample project : https://github.com/juvilux/Growtopia-Save.dat-Stealer

**Comment by enitemma** [comment]
Great idea! Probably wouldn't be the best same since it uses a client that has to be running 24/7.

**Comment by Altanb1337** [comment]
> Great idea! Probably wouldn't be the best same since it uses a client that has to be running 24/7.

client no need to run 24/7

**Comment by enitemma** [comment]
In the source you sent there Is a client and  server. For the server to be able to recieve / send data you need the client running.

**Comment by extatent** [comment]
Use a proper obfuscator. You can fork the project and add the function.
